### ISSUE TITLE
Endorsement questionaire

### ISSUE THREAD

**Issue by zopa** [InTheFight/ITF-website#1]
For our endorsement process, we ask campaigns to submit a questionnaire with contact info, basic details of the race and candidate, and some issue questions. We'd like to have an online form to handle this, with the data stored in some convenient form. 

Here's the draft list of questions:
https://docs.google.com/document/d/1wCacbQ_f6xGrQbUdz3Fb8cuS13ElmO9sQ1zYaMtq5CM

**Comment by rgardaphe** [comment]
Hey gang - anything The electoral team can do to move this along? shall we set up a meeting to discuss the right ideas to code this up and access the data that comes from it? --thaaaaanks

**Comment by rgardaphe** [comment]
Let's throw this at the top of the endorsement page, above the questions:

-------------------------

Thank you for your interest in earning an endorsement from In The Fight North Brooklyn!

Please complete the questionnaire below and submit your answers. If invited to interview with our members, a member of the ITF-NBK electoral team will be in touch via the email you provide below.

An endorsement from In the Fight North Brooklyn comes with our organization's commitment of time, resources, and mutual support. We focus on endorsing in local elections that impact our North Brooklyn community. 

We are currently focusing on speaking with candidates for the following offices:

 - Mayor
 - Public Advocate
 - Comptroller
 - Brooklyn Borough President
 - City Council Districts: 33, 34, 35, 36 & 37

If you are a candidate for an office not listed above, give us a shout! We routinely support candidates that share our values, and would love to get involved and see how we can work together. 

If you have any issues with the questionnaire or need to contact us, you can reach us at electoral@inthefight.org.

**Comment by fridaland** [comment]
Closing this as endorsements page is up: https://endorsements.inthefight.org/endorsement-questionnaire/
