### ISSUE TITLE
Eliminate election/primary date question

### ISSUE THREAD

**Issue by rgardaphe** [InTheFight/ITF-website#11]
We'd like to eliminate this question because it causes confusion as currently constructed, and would not provide valuable data since every race for this cycle is on the same date.

**Comment by zopa** [comment]
I've got a fix to just remove it, which we'll need to do on the database side as well.

Another option would be to hide the question from users, but submit the one-true-correct election date along with the form, so we have it on the backend.

Pros: Might help us keep questionnaires straight once we have more than one election date.  

Cons: We'd have to keep it up to date, or else things would get very confusing

**Comment by rgardaphe** [comment]
I like that - yes, let's have tthe one-true-correct election date on the backend. Good idea.

**Comment by zopa** [comment]
Leaving this for next cycle at this point
