### ISSUE TITLE
Submission confirmation

### ISSUE THREAD

**Issue by rgardaphe** [InTheFight/ITF-website#12]
It'd be great if upon pressing submit, the user is offered a confirmation and the following message:

"Thank you! Your answers have been submitted."

**Comment by zopa** [comment]
Current version _mostly_ works, but the submit message is overeager. The success message displays as soon as we launch the network request; when there's an error, we then switch to the failure notification when the network request failure arrives a second or two later. Better would be "Submitting..." until we hear back from the database, and then either Success or Failure as needed

**Comment by fridaland** [comment]
Fixed with #22
