### ISSUE TITLE
Revision to: "District Number" Question

### ISSUE THREAD

**Issue by rgardaphe** [InTheFight/ITF-website#7]
“District Number, if applicable” doesn’t allow you to enter a non-numerical answer. 

Can we make the drop-down choices instead as follows: 
33
34
35
36
37
Other
N/A

**Comment by zopa** [comment]
We could, but what does 'Other' mean? It'd be natural to have 'Other [text box appears so they can explain]', and that's possible, but I've been putting off implementing that sort of thing as nice to have but too complicated for now.

But if we're happy with a no-further-info 'Other', that's an easy change

**Comment by Pianonurse** [comment]
A no-futher-info other is fine for now. For now we just want to know if they are applying for a district we are endorsing in.

**Comment by fridaland** [comment]
Disregard -  going to favor #2
