### ISSUE TITLE
Bug: No text box next to "Tell us about who you are" question

### ISSUE THREAD

**Issue by rgardaphe** [InTheFight/ITF-website#8]
“Tell us about who you are and why you are running. Include your core values and vision.” question doesn’t have a text box to answer

**Comment by zopa** [comment]
Per the [draft questionnaire doc](https://docs.google.com/document/d/1wCacbQ_f6xGrQbUdz3Fb8cuS13ElmO9sQ1zYaMtq5CM), this is one question, in two paragraphs. Do we want to split it in two?

**Comment by rgardaphe** [comment]
Oh that's right. Can we just make this one paragraph then?

**Comment by zopa** [comment]
We sure can, but I think with the addition of question numbers it's not confusing any more. Concur?

**Comment by rgardaphe** [comment]
Concur. Let's close this issue.
